### ISSUE TITLE
[PE-D][Tester D] Bug with phone numbers

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W16-1/tp#154]
![image.png](https://raw.githubusercontent.com/mohamedsaf1/ped/main/files/35592019-0768-473a-8128-cf1f0c4dbe56.png)

Phone numbers of diff length can be added, although it might not necessarily be valid. Maybe the length of phone numbers can be fixed, or the country code can be indicated in UG.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: mohamedsaf1/ped#1

**Comment by jehousoh** [comment]
This is not a bug and is an intended feature of GuestBook to allow for flexibility.
