### ISSUE TITLE
[PE-D][Tester A] Editing a person with the same values it has does not show an error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-1/tp#160]
With the default data. Doing `edit 1 n/Alex Yeoh` does not show that nothing was edited since the name of the person at index 1 is also "Alex Yeoh".

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: KeithPJX/ped#3

**Comment by jehousoh** [comment]
We do not feel that this is a bug.
