### ISSUE TITLE
[PE-D][Tester D] Table of Contents might be incomplete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-1/tp#166]
![image.png](https://raw.githubusercontent.com/mohamedsaf1/ped/main/files/edb10d87-e816-4fd9-b322-11e262c94828.png)

Table of contents is not detailed. Highly unlikely to be incomplete

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: mohamedsaf1/ped#4

**Comment by jehousoh** [comment]
This is a Github markdown format feature that helps generate the table of contents for the actual html page, hence it is not a bug.
