### ISSUE TITLE
[PE-D][Tester A] Put a limit on the length of characters for rooms

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-1/tp#171]
![image.png](https://raw.githubusercontent.com/KeithPJX/ped/main/files/d7b943a5-3cc8-40cf-90dc-9d5a1cc9e691.png)

Not really a bug but a suggestion. I guess this is just a user being dumb but you can consider doing this.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: KeithPJX/ped#5

**Comment by jehousoh** [comment]
Limit room to 100 characters
